ci:
    autofix_prs: false


repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    # unlike most pre-commit tools, the version of this repository exactly
    # matches the version of clang-format
    rev: v17.0.1
    hooks:
    -   id: clang-format
        verbose: true
        types_or: [c++, c, cuda]
        args: ["-style=file", "--verbose"]

